# docker-compose.yml

version: '3.9'

services:
  # 1. Сервис Базы Данных (PostgreSQL)
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    env_file:
      - .env
    restart: always

  # 2. Сервис Redis
  redis:
    image: redis:7-alpine
    restart: always

  # 3. Сервис Django (назовем его 'web')
  web:
    build: .
    command: sh /app/entrypoint.sh # Будем запускать через скрипт
    volumes:
      - .:/app
      - static_volume:/app/static_volume
      - media_volume:/app/media_volume
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - db
      - redis
    restart: on-failure

  # 4. Сервис Celery Worker
  celery:
    build: .
    command: celery -A Config worker -l info
    stop_signal: SIGKILL
    volumes:
      - .:/app
      - media_volume:/app/media_volume
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - web
      - redis
    restart: on-failure

  # 5. Сервис Nginx
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static_volume
      - media_volume:/app/media_volume
    ports:
      - "80:80" # <-- Теперь сайт будет доступен на порту 80
    depends_on:
      - web
    restart: always

# Определяем "тома" (volumes) для персистентного хранения данных
volumes:
  postgres_data:
  static_volume:
  media_volume: