# Generated by Django 5.2.6 on 2025-10-01 14:26

import django.core.validators
import django.db.models.deletion
import src.core.untils.my_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_banner', models.CharField(help_text='Input name Banner', max_length=50, validators=[django.core.validators.MinLengthValidator(1)])),
                ('status_banner', models.BooleanField(default=True, help_text='Select status Banner')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
            },
            bases=(models.Model, src.core.untils.my_validator.UrlValidatorMixin, src.core.untils.my_validator.CounterValidatorMixin),
        ),
        migrations.CreateModel(
            name='BackgroundBanner',
            fields=[
                ('banners_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banner.banners')),
                ('image_banner', models.ImageField(blank=True, help_text='Upload an image. Supported formats: JPEG, PNG', null=True, upload_to='backgrounds/')),
                ('color', models.CharField(blank=True, help_text='Color name or HEX, e.g. red or #ff0000', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'background banner',
                'verbose_name_plural': 'background banners',
            },
            bases=('banner.banners',),
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('banners_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banner.banners')),
                ('url_banner', models.URLField(blank=True, help_text='Input url Banner', max_length=300, null=True)),
                ('text_banner', models.TextField(blank=True, help_text='Input text to Banner', null=True)),
                ('speed_banner', models.IntegerField(blank=True, default=5, help_text='Input speed to Banner', null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'home banner slide',
                'verbose_name_plural': 'home banner slides',
            },
            bases=('banner.banners',),
        ),
        migrations.CreateModel(
            name='HomeNewsSharesBanner',
            fields=[
                ('banners_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banner.banners')),
                ('url_banner', models.URLField(blank=True, help_text='Input url Banner', max_length=300, null=True)),
                ('speed_banner', models.IntegerField(blank=True, default=5, help_text='Input speed to Banner', null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'home news/shares slide',
                'verbose_name_plural': 'home news/shares slides',
            },
            bases=('banner.banners',),
        ),
    ]
