# Generated by Django 5.2.5 on 2025-09-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homenewssharesbanner',
            options={'verbose_name': 'home banner', 'verbose_name_plural': 'home banners'},
        ),
        migrations.AddField(
            model_name='backgroundbanner',
            name='color',
            field=models.CharField(blank=True, help_text='Color name or HEX, e.g. red or #ff0000', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='backgroundbanner',
            name='image_banner',
            field=models.ImageField(blank=True, help_text='Upload an image. Supported formats: JPEG, PNG', null=True, upload_to='static/image/'),
        ),
        migrations.AlterField(
            model_name='homenewssharesbanner',
            name='url_banner',
            field=models.URLField(blank=True, help_text='Input url Banner', max_length=300, null=True),
        ),
    ]
