# Generated by Django 5.2.6 on 2025-10-01 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('coords', models.CharField(blank=True, max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='contacts/logos/')),
                ('status', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('seo_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.seoblock')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['time_created'],
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(max_length=11)),
                ('phone2', models.CharField(max_length=11)),
                ('seo_text', models.TextField()),
                ('seo_text_ru', models.TextField(null=True)),
                ('seo_text_en', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('seo_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPromotionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_promotion', models.BooleanField(default=False, help_text='Отметьте, если это акция. Иначе запись будет считаться новостью.', verbose_name='Это акция?')),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_ru', models.CharField(max_length=50, null=True, unique=True)),
                ('name_en', models.CharField(max_length=50, null=True, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='news_promotion/')),
                ('url_movie', models.URLField(blank=True, help_text='Input url movie', max_length=300, null=True)),
                ('gallery_banner', models.OneToOneField(blank=True, help_text='Select Gallery to Banner', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gallery')),
                ('seo_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='OtherPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='pages/main/')),
                ('status', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gallery')),
                ('seo_block', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.seoblock')),
            ],
            options={
                'verbose_name': 'другая страница',
                'verbose_name_plural': 'другие страницы',
            },
        ),
    ]
