"""
Django settings for Kino_CMS project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q)7@blc#jmh#4y@%wloc_6k-_&%_a1mwzu88o50l11pw@58s9r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    # Базовые шаблоны и теги (ставим раньше всего)
    "adminlte4",
    # Тема для стандартной админки (обязательно ДО 'django.contrib.admin')
    "adminlte4_theme",
    'users',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "main.apps.MainConfig"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ADMINLTE4_MENU = [
    {"name": "Статистика", "url": "/admin/", "icon": "fas fa-chart-line"},
    {"name": "Баннеры/Слайдеры", "url": "/admin/banners/banner/", "icon": "fas fa-images"},
    {"name": "Фильмы", "url": "/admin/movies/movie/", "icon": "fas fa-film"},
    {"name": "Кинотеатры", "url": "/admin/cinemas/cinema/", "icon": "fas fa-video"},
    {"name": "Новости", "url": "/admin/news/news/", "icon": "fas fa-newspaper"},
    {"name": "Акции", "url": "/admin/promotions/promotion/", "icon": "fas fa-tags"},
    {"name": "Страницы", "url": "/admin/pages/page/", "icon": "fas fa-file-alt"},
    {"name": "Пользователи", "url": "/admin/auth/user/", "icon": "fas fa-users"},
    {"name": "Рассылка", "url": "/admin/mailing/mailing/", "icon": "fas fa-envelope"},
]


ROOT_URLCONF = 'Kino_CMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Kino_CMS.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # },
    'default': {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "kinocms",
        "USER": "admin",
        "PASSWORD": "admin",
        "HOST": "localhost",
        "PORT": "5432"
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        # 'OPTIONS': {
        #     'min_lenght':8,
        # }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGES = [
    ('ru', 'Russian'),
    ('en', 'English'),
    # Добавьте другие нужные языки
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

AUTH_USER_MODEL = 'users.CustomUser'


# (Опционально) Настройки для хранения языка
# SESSION_COOKIE_AGE = 1209600 # 2 недели
# LANGUAGE_COOKIE_NAME = 'django_language' # Имя cookie
# LANGUAGE_COOKIE_AGE = 1209600 # Срок жизни cookie
# LANGUAGE_COOKIE_DOMAIN = None # Домен cookie
# LANGUAGE_COOKIE_PATH = '/' # Путь cookie
# LANGUAGE_COOKIE_SECURE = False # Требовать HTTPS
# LANGUAGE_COOKIE_HTTPONLY = False # Доступен только через HTTP
# LANGUAGE_COOKIE_SAMESITE = None # Атрибут SameSite