# Generated by Django 5.2.5 on 2025-09-02 08:23

import django.core.validators
import django.db.models.deletion
import src.core.untils.my_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_gallery', models.CharField(help_text='Input name Gallery', max_length=300, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'gallerys',
            },
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_seo', models.URLField(blank=True, help_text='Input url address SEO', null=True)),
                ('title_seo', models.CharField(help_text='Input title SEO', max_length=300, validators=[django.core.validators.MinLengthValidator(1)])),
                ('keywords_seo', models.CharField(blank=True, help_text='Input keywords SEO', max_length=400, null=True, validators=[src.core.untils.my_validator.SeoValidator.validate_keywords])),
                ('description_seo', models.TextField(blank=True, help_text='Input description SEO', null=True)),
            ],
            bases=(models.Model, src.core.untils.my_validator.UrlValidatorMixin),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gallery')),
            ],
            options={
                'verbose_name': 'gallery_image',
                'verbose_name_plural': 'gallery_images',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image. Supported formats: JPEG, PNG', null=True, upload_to='static/images/')),
                ('gallery', models.ManyToManyField(help_text='Select Gallery', through='core.GalleryImage', to='core.gallery')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
            bases=(models.Model, src.core.untils.my_validator.ImageValidatorMixin),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.image'),
        ),
    ]
