# Generated by Django 5.2.6 on 2025-10-01 15:21

import django.db.models.deletion
import src.core.untils.my_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_gallery', models.CharField(help_text='Input name Gallery', max_length=300)),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
            },
        ),
        migrations.CreateModel(
            name='MailingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('file', models.FileField(upload_to='mailing_templates/', verbose_name='HTML файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Шаблон рассылки',
                'verbose_name_plural': 'Шаблоны рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Уникальный slug для SEO блока (например: 'about-us', 'contacts')", max_length=255, unique=True, verbose_name='URL (slug)')),
                ('title_seo', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title')),
                ('title_seo_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title')),
                ('title_seo_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title')),
                ('keywords_seo', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('keywords_seo_ru', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('keywords_seo_en', models.TextField(blank=True, null=True, verbose_name='SEO Keywords')),
                ('description_seo', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('description_seo_ru', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('description_seo_en', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image.', null=True, upload_to='gallery_images/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.gallery')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
            bases=(models.Model, src.core.untils.my_validator.ImageValidatorMixin),
        ),
        migrations.CreateModel(
            name='MailingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID задачи Celery')),
                ('send_to_all', models.BooleanField(default=True, verbose_name='Отправить всем')),
                ('recipients', models.JSONField(blank=True, null=True, verbose_name='Получатели (ID)')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='Всего получателей')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Отправлено писем')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время старта')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('templates', models.ManyToManyField(to='core.mailingtemplate', verbose_name='Шаблоны')),
            ],
            options={
                'verbose_name': 'Кампания рассылки',
                'verbose_name_plural': 'Кампании рассылки',
                'ordering': ['-started_at'],
            },
        ),
    ]
